// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXtFWIZxBRyL_QDQ23LVPPko5ETrWcNxU',
    appId: '1:674058382440:web:c5e09a764ed75555c35fdd',
    messagingSenderId: '674058382440',
    projectId: 'first-project-4aabf',
    authDomain: 'first-project-4aabf.firebaseapp.com',
    storageBucket: 'first-project-4aabf.appspot.com',
    measurementId: 'G-797R3T719N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFxq4d3aO42d6tOAqV9q2mSf-XhvTHk_Q',
    appId: '1:674058382440:android:b0bbcb1fa5f7e1e8c35fdd',
    messagingSenderId: '674058382440',
    projectId: 'first-project-4aabf',
    storageBucket: 'first-project-4aabf.appspot.com',
  );
}
